
services:
  - docker

env:
  global:
    - ALGERNON_VERSION=${ALGERNON_VERSION:-1.11.0}
    - BUILD_DATE=$(date +"%Y-%m-%d")

jobs:
  include:

    - stage: build
      script:
        - make

    - stage: build and push image
      script:
        - make
        - docker tag ${DOCKER_USERNAME}/docker-algernon:${ALGERNON_VERSION} ${DOCKER_USERNAME}/docker-algernon:latest
        - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
        - docker push ${DOCKER_USERNAME}/docker-algernon:${ALGERNON_VERSION}
        - docker push ${DOCKER_USERNAME}/docker-algernon:latest
        - docker logout

