---
version: '3.3'

services:

  algernon:
    restart: always
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - VCS_REF=${GIT_SHA1}
        - BUILD_DATE=${BUILD_DATE}
        - BUILD_VERSION=${BUILD_VERSION}
        - BUILD_TYPE=${BUILD_TYPE}
        - ALGERNON_VERSION=${ALGERNON_VERSION}
    container_name: algernon
    hostname: algernon
    entrypoint: '/usr/bin/algernon'
    command:
      - '--simple'
      - '--addr=:8080'
      - '--dir=/data'
    volumes:
      - ../data:/data
    ports:
      - 8080:8080
