#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

cat << EOF > .env

BUILD_DATE=${BUILD_DATE}
BUILD_VERSION=${BUILD_VERSION}
BUILD_TYPE=stable
ALGERNON_VERSION=${ALGERNON_VERSION}

EOF

docker-compose \
  --file compose/head.yml \
  --file compose/algernon.yml \
  config > docker-compose.yml
